[2024-02-02T14:57:36.245+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: final_project.Load_songplays_fact_table scheduled__2018-11-01T03:00:00+00:00 [queued]>
[2024-02-02T14:57:36.322+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: final_project.Load_songplays_fact_table scheduled__2018-11-01T03:00:00+00:00 [queued]>
[2024-02-02T14:57:36.327+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 4
[2024-02-02T14:57:36.373+0000] {taskinstance.py:1350} INFO - Executing <Task(LoadFactOperator): Load_songplays_fact_table> on 2018-11-01 03:00:00+00:00
[2024-02-02T14:57:36.427+0000] {standard_task_runner.py:57} INFO - Started process 778 to run task
[2024-02-02T14:57:36.463+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'final_project', 'Load_songplays_fact_table', 'scheduled__2018-11-01T03:00:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/final_project.py', '--cfg-path', '/tmp/tmpw6w_h5bm']
[2024-02-02T14:57:36.481+0000] {standard_task_runner.py:85} INFO - Job 40: Subtask Load_songplays_fact_table
[2024-02-02T14:57:37.264+0000] {task_command.py:410} INFO - Running <TaskInstance: final_project.Load_songplays_fact_table scheduled__2018-11-01T03:00:00+00:00 [running]> on host daef2c2ad421
[2024-02-02T14:57:38.087+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Philip' AIRFLOW_CTX_DAG_ID='final_project' AIRFLOW_CTX_TASK_ID='Load_songplays_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2018-11-01T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2018-11-01T03:00:00+00:00'
[2024-02-02T14:57:38.104+0000] {load_fact.py:22} INFO - Clearing data from destination Redshift table
[2024-02-02T14:57:38.166+0000] {base.py:73} INFO - Using connection ID 'redshift' for task execution.
[2024-02-02T14:57:38.185+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/load_fact.py", line 23, in execute
    redshift_hook.run("TRUNCATE {}".format(self.table))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 342, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 144, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "default-workgroup.434192172683.us-east-1.redshift-serverless.amazonaws.com" to address: Name or service not known

[2024-02-02T14:57:38.224+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=final_project, task_id=Load_songplays_fact_table, execution_date=20181101T030000, start_date=20240202T145736, end_date=20240202T145738
[2024-02-02T14:57:38.259+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 40 for task Load_songplays_fact_table (could not translate host name "default-workgroup.434192172683.us-east-1.redshift-serverless.amazonaws.com" to address: Name or service not known
; 778)
[2024-02-02T14:57:38.344+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2024-02-02T14:57:38.532+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
